//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analyse
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public double PulseRate { get; set; }
        public int Systolic { get; set; }
        public int Diastolic { get; set; }
        public bool Abnormality { get; set; }
        public bool Reliability { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
